### ISSUE TITLE
Stuck on settings dialogue after the very first admin login

### ISSUE THREAD

**Issue by iamshery** [drkNsubuga/PharmaSpot#20]
After filling in the settings dialogue at first start, nothing happens on pressing the submit button.

**Comment by drkNsubuga** [comment]
Sorry about that. Just for context, can you please provide a little more details on the environment  & application version you are using?

**Comment by iamshery** [comment]
Thank you for your prompt reply.
I am using Pharmaspot v1.4.0 on Windows 10
Application launches normally but after filling in the settings dialogue, I am unable to save changes. Pressing save settings button does nothing. I am attaching a screenshot of the screen.
![screenshot](https://github.com/drkNsubuga/PharmaSpot/assets/41643976/e8f8e4b0-9117-401d-91f2-45e64791991b)

**Comment by drkNsubuga** [comment]
I've noted on my end too and it's gonna be fixed.

**Comment by iamshery** [comment]
Thank you.

**Comment by drkNsubuga** [comment]
This has been fixed in the latest version

**Comment by glezeus** [comment]
I am still having this problem with the latest version 1.4.1. 
After filling all the boxes the button "Save Settings" doesn't work.

**Comment by drkNsubuga** [comment]
Sorry about this! Which OS are you currently using?

**Comment by glezeus** [comment]
Thank you! I am currently using Windows 10

**Comment by basanteop** [comment]
Issue still persit on windows

**Comment by drkNsubuga** [comment]
Can you please provide details on your environment? Pharmspot version and OS. Is this happening during development or in the production release?
